AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Frontend CI/CD
Parameters:
  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String

  GitHubToken:
    Type: String

  GitHubUser:
    Type: String

Resources:

  albumbucketkerwin:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: albumbucketkerwin
    
  albumbucketkerwin2:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: albumbucketkerwin2
  
  photo_search_api_gateway:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt 
        - MyApi
        - RootResourceId
      PathPart: stack

  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: src_search/
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::993611456293:role/service-role/search-photos-role-d2ojh1u9'
      Layers:
        - 'arn:aws:lambda:us-east-1:993611456293:layer:mylayer:2'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: src_index/
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::993611456293:role/AlbumRole'
      Layers:
        - 'arn:aws:lambda:us-east-1:993611456293:layer:mylayer:2'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

